---
- name: Chequear website 
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Hacemos ping al servidor web
    command: ping web.expertice.local -c 1
    register: salida_ping
 
  - name: Curl website
    command: curl "http://web.expertice.local"
    register: webpage
  
  - debug: 
     var: salida_ping.stdout_lines 
      
  
  - name: Fail
    fail:
    when: "'Nuestro' not in webpage.stdout" 
  
  - name: Success
    debug: msg="Felicidades, su website esta en funcionamiento!"
