---
- name: Desinstala Apache httpd
  gather_facts: no
  hosts: "{{ servidor }}"
  vars:
   servidor: server 
  tasks:
  - name: Detenemos el Apache.
    service:
     name: httpd
     state: stopped

  - name: Desinstala Apache
    package:
     name: httpd
     state: absent     

  - name: Retirar servicios http/https del firewall
    command: 
     firewall-cmd --permanent --remove-service=http  --remove-service=https
    notify: firewalld reload

  - name: Removemos los archivos viejos del site productivo.
    file:
      path: /var/www/html/index.html
      state: absent

  
  handlers:
  - name: firewalld reload
    command: firewall-cmd --reload



