---
- name: Desinstala Apache httpd
  gather_facts: no
  hosts: "{{ servidor }}"
#  vars:
#   servidor: server 
  tasks:
  - name: Desinstala httpd
    package:
      name: httpd
      state: absent
  
  - name: Retirar servicios http/https del firewall
    command: 
     firewall-cmd --permanent --remove-service=http  --remove-service=https
    notify: firewalld reload

  - name: Remove los archivos del site
    file:
      path: /var/www/html/index.html
      state: absent

  
  handlers:
  - name: firewalld reload
    command: firewall-cmd --reload



