---
- name: Instala y Configura WebServer 
  hosts: all
  tasks:
  - name: Copy static index.html to Webserver
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      mode: 0644
