- hosts: db_servers
  become: yes
#  vars_files:
#    - /var/lib/awx/projects/roles/geerlingguy.mysql/vars/main.yml
  roles:
    - { role: geerlingguy.mysql }

#- name: Instalar y Configurar Mariadb
#  hosts: db_servers
#  roles:
#    - role: geerlingguy.mysql
#      become: yes
