---
- name: Telegram Notifications ok
  hosts: all
  tasks:
  - name: send a message to chat in playbook
    telegram:
      token: '1291052384:AAEFHpnvwdV3YsYpOmnz1szVlAL1GZOq60I'
      chat_id: 756926933
      msg: "lanzamiento {{ tower_workflow_job_name }} ID {{ tower_workflow_job_id }} Finalizó Satisfactoriamente el {{ansible_date_time.date}} por el usuario {{ tower_user_name }} "
