mysql_root_password: root
mysql_databases:
  - name: mydb
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: root
    host: "%"
    password: root
    priv: "example_db.*:ALL"
